version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    ports:
      - 8000:8000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    command:
      - bash
      - -c
      - |
        composer install;
        php artisan migrate;
        php artisan serve --host 0.0.0.0

  redis:
    image:
      redis:5.0.4
    ports:
      - 6379:6379
    healthcheck:
      test: "exit 0"

  node:
    image: node:12.16.0
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command:
      - bash
      - -c
      - |
        yarn

  db:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: America/Los_Angeles
    healthcheck:
      test: "exit 0"

  phpmyadmin:
    image:
      phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "${PHP_MYADMIN_PORT}:80"


volumes:
  data: {}
  esdata: {}

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
